#!/bin/sh -e

cd "$(dirname "$0")/.."
PATH=$PWD/scripts/node_modules/.bin:$PATH

recipes() {
    for path in recipes/*.md; do
        title=$(head -1 "$path" | sed 's/..//')
        echo "$title: $path $title"
    done
}

recipe=$(recipes | prompts select --message Recipe)
path=$(echo "$recipe" | cut -d' ' -f1)
title=$(echo "$recipe" | cut -d' ' -f2-)

sed -n '/^## .*Ingredients/,/^#/p' "$path" | grep '^*'

label=$(grep '\*\*Label:\*\* ' "$path" | sed 's/.*:\*\* //')
label=$(prompts text --message Label --initial "$label")

color=$(printf 'Red: red\nGreen: green\nBlue: blue\nYellow: yellow\nPurple: purple' | prompts select --message 'Color')
date_time=$(prompts date --message 'Brewing date')
date=$(echo "$date_time" | sed 's/ .*//')
year=$(echo "$date" | sed 's/-.*//')

base=$(basename "$path")

mkdir -p "batches/$year"

cat > "batches/$year/$date-$base" << EOF
# $date - $title

* **Recipe:** [$title](../../$path)
* **Label:** $label
* **Color:** $color
* **Brewing:** $date_time
* **Fermenting:**
* **Bottling:**
* **Chilling:**
EOF
