#!/bin/sh -e

cd "$(dirname "$0")/.."
PATH=$PWD/scripts/node_modules/.bin:$PATH

batches_or_error() {
    grep -RL '^## Bottles' batches | while read path; do
        title=$(head -1 "$path" | sed 's/..//')
        echo "$title: $path"
    done | grep . || {
        echo 'Nothing to bottle!' >&2
        exit 1
    }
}

bottles_list() {
    echo '1 L'
    echo '750 ml'
    echo '500 ml'
    echo 'Growler (64 fl oz)'
}

bottles() {
    bottles_list | prompts countableMultiselect --message 'Bottles' --min 1 --instructions false
}

batches=$(batches_or_error)
path=$(echo "$batches" | prompts select --message Batch)
label=$(grep '\*\*Label:\*\* ' "$path" | sed 's/.*:\*\* //')
date_time=$(prompts date --message 'Bottling date')
counter=$(find bottles -type l | wc -l)
counter=$((counter+0)) # Cast as number without spaces

sed -i.bottle "s/Bottling:\*\*.*/Bottling:** $date_time/" "$path"
rm "$path.bottle"

bottles=$(bottles)

printf '\n## Bottles\n\n' >> "$path"

echo "$bottles" | while read count type; do
    for _ in $(seq 1 "$count"); do
        echo "$type [$label] [#$counter]"
        echo "* $type **[#$counter]**" >> "$path"
        ln -s "../$path" "bottles/$counter.md"
        counter=$((counter+1))
    done
done
