#!/bin/sh -e

cd "$(dirname "$0")/.."
PATH=$PWD/scripts/node_modules/.bin:$PATH

batches_or_error() {
    grep -Rl 'Chilling:\*\*$' batches | while read path; do
        title=$(head -1 "$path" | sed 's/..//')
        echo "$title: $path"
    done | grep . || {
        echo 'Nothing to chill!' >&2
        exit 1
    }
}

batches=$(batches_or_error)
path=$(echo "$batches" | prompts select --message Batch)
date_time=$(prompts date --message 'Chilling date')

sed -i.ferment "/Chilling:/s/$/ $date_time/" "$path"
rm "$path.ferment"
