#!/bin/sh -e

PROGDIR=$(readlink -f "$(dirname "$0")")
PATH=$PROGDIR/node_modules/.bin:$PATH
cd "$PROGDIR/.."

batches_or_error() {
    grep -Rl ':\*\*$' batches | grep . || {
        echo 'Nothing to do!' >&2
        exit 1
    }
}

batches=$(batches_or_error)

for batch in $batches; do
    printf "$batch: "
    node scripts/sup.js "$batch"
done
