#!/bin/sh -e

cd "$(dirname "$0")/.."

batches_or_error() {
    grep -Rl ':\*\*$' batches | sort | grep . || {
        echo 'Nothing to do!' >&2
        exit 1
    }
}

batches=$(batches_or_error)

node scripts/sup.js $batches
