#!/bin/sh -e

cd "$(dirname "$0")/.."

sed -n '1,/^## .*Upcoming batches/p' README.md
echo

grep -RL '^## Bottles' batches | sort | while read path; do
    title=$(head -1 "$path" | sed 's/# [^ ]* - //')
    label=$(grep '\*\*Label:\*\* ' "$path" | sed 's/.*:\*\* //')
    echo "* [$title **[$label]**]($path)"
done

echo
grep '## .*Latest batches' README.md
echo

grep -Rl '## Bottles' batches | sort -r | head -5 | while read path; do
    title=$(head -1 "$path" | sed 's/# [^ ]* - //')
    label=$(grep '\*\*Label:\*\* ' "$path" | sed 's/.*:\*\* //')
    bottling=$(grep '\*\*Bottling:\*\* ' "$path" | sed 's/.*:\*\* //' | cut -d' ' -f1)
    echo "* $bottling [$title **[$label]**]($path)"
done

echo
sed -n '/^## .*Philosophy/,$p' README.md
